app = "tris-blue-hill-1918"
primary_region = "otp"

[build]
  image = "vmandic/tris:latest"
  ignorefile = "./docker/.dockerignore"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.ports]]
    handlers = ["tls"]
    start_port = 8080
    end_port = 8082
    tls_options = { "default_self_signed" = true }

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
